const menu = [
  // * Desayuno
  {
    nombre: "Panuozzo",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB01",
    precio: 50,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Un vino blanco dulce como Sauternes o Barsac",
  },
  {
    nombre: "Huevo Benedicto Trove",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB02",
    precio: 45,
    calificacion: 4,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Café con leche o jugo de naranja fresco",
  },
  {
    nombre: "Tostada De Aguacate Sobre Pan De Masa Madre",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB03",
    precio: 30,
    calificacion: 4.5,
    tiempoDePreparacion: "15 minutos",
    maridajeSugerido: "Té verde o smoothie de frutas",
  },
  {
    nombre: "Peanana",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB04",
    precio: 55,
    calificacion: 5,
    tiempoDePreparacion: "25 minutos",
    maridajeSugerido: "Michelada o jugo de tomate",
  },
  {
    nombre: "Croissant simple",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB05",
    precio: 40,
    calificacion: 4.7,
    tiempoDePreparacion: "45 minutos",
    maridajeSugerido: "Café americano o té chai",
  },
  {
    nombre: "hummus",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB06",
    precio: 50,
    calificacion: 4.8,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Café espresso o chocolate caliente",
  },
  {
    nombre: "Rollos de Paratha",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB07",
    precio: 35,
    calificacion: 4,
    tiempoDePreparacion: "10 minutos",
    maridajeSugerido: "Infusión de frutas o café frío",
  },
  {
    nombre: "Croissant Nutella",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB08",
    precio: 60,
    calificacion: 5,
    tiempoDePreparacion: "35 minutos",
    maridajeSugerido: "Jugo de manzana o té negro",
  },
  {
    nombre: "Tazón cetogénico",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB09",
    precio: 45,
    calificacion: 4.6,
    tiempoDePreparacion: "40 minutos",
    maridajeSugerido: "Vino blanco seco o limonada",
  },
  {
    nombre: "Rollos de Paratha",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB10",
    precio: 65,
    calificacion: 4.9,
    tiempoDePreparacion: "15 minutos",
    maridajeSugerido: "Café con crema o té de menta",
  },
  {
    nombre: "Yogur griego con miel y granola",
    categoria: "Desayuno",
    imagen: "url_de_la_imagen",
    codigo: "DB11",
    precio: 55,
    calificacion: 4.3,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Zumo de zanahoria o agua de coco",
  },
  // * Ensalada
  {
    nombre: "Ensalada griega",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "FGTN01",
    precio: 50,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Un vino blanco dulce como Sauternes o Barsac",
  },
  {
    nombre: "Ensalada de Langosta y Mango",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "ELMG02",
    precio: 120,
    calificacion: 5,
    tiempoDePreparacion: "45 minutos",
    maridajeSugerido: "Champán o un Chardonnay bien frío",
  },
  {
    nombre: "Carpaccio de Res con Rúcula",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "CBRR03",
    precio: 85,
    calificacion: 5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Vino tinto de cuerpo medio como Merlot",
  },
  {
    nombre: "Ensalada de Quinoa Real con Aguacate",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "EQRA04",
    precio: 70,
    calificacion: 4.8,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Vino blanco aromático como Sauvignon Blanc",
  },
  {
    nombre: "Ensalada César con Pollo a la Parrilla",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "ECPP05",
    precio: 65,
    calificacion: 4.7,
    tiempoDePreparacion: "25 minutos",
    maridajeSugerido: "Rosado seco o un Pinot Grigio",
  },
  {
    nombre: "Ensalada de Burrata con Tomate Heirloom",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "EBTH06",
    precio: 90,
    calificacion: 5,
    tiempoDePreparacion: "15 minutos",
    maridajeSugerido: "Prosecco o un vino blanco ligero",
  },
  {
    nombre: "Ensalada de Remolacha y Cabra",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "ERCC07",
    precio: 75,
    calificacion: 4.9,
    tiempoDePreparacion: "40 minutos",
    maridajeSugerido: "Riesling o un vino espumoso",
  },
  {
    nombre: "Ensalada Waldorf Moderna",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "EWMD08",
    precio: 80,
    calificacion: 4.6,
    tiempoDePreparacion: "35 minutos",
    maridajeSugerido: "Vino blanco seco o un cóctel ligero",
  },
  {
    nombre: "Ensalada de Espinacas con Fresas y Nueces",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "EEFN09",
    precio: 55,
    calificacion: 4.5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Vino rosado o un Sauvignon Blanc",
  },
  {
    nombre: "Ensalada de Pulpo a la Gallega",
    categoria: "Ensalada",
    imagen: "url_de_la_imagen",
    codigo: "EPG10",
    precio: 110,
    calificacion: 5,
    tiempoDePreparacion: "50 minutos",
    maridajeSugerido: "Albariño o un vino blanco gallego",
  },
  // * Entrante
  {
    nombre: "Tartar De Salmón",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN01",
    precio: 50,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Un vino blanco dulce como Sauternes o Barsac",
  },
  {
    nombre: "Camarones Dinamita",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN02",
    precio: 150,
    calificacion: 5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Vino tinto reserva o sake premium",
  },
  {
    nombre: "Ceviche Trío De Maíz Y Atún",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN03",
    precio: 130,
    calificacion: 5,
    tiempoDePreparacion: "25 minutos",
    maridajeSugerido: "Vino de postre como Tokaji o un Oporto vintage",
  },
  {
    nombre: "Tartaro Wagyu",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN04",
    precio: 120,
    calificacion: 5,
    tiempoDePreparacion: "15 minutos",
    maridajeSugerido: "Champán brut o un Chablis",
  },
  {
    nombre: "Burrata crujiente",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN05",
    precio: 140,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Vino blanco frío como un Pinot Grigio o un Vermentino",
  },
  {
    nombre: "Calamares fritos",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN06",
    precio: 200,
    calificacion: 5,
    tiempoDePreparacion: "35 minutos",
    maridajeSugerido: "Vodka premium frío o un vino espumoso seco",
  },
  {
    nombre: "Pulpo a la brasa",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN07",
    precio: 160,
    calificacion: 5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Sake Junmai Daiginjo o un Riesling joven",
  },
  {
    nombre: "Rollo de trufa Wagyu",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN08",
    precio: 110,
    calificacion: 5,
    tiempoDePreparacion: "25 minutos",
    maridajeSugerido: "Cerveza lager japonesa o un vino blanco como Albariño",
  },
  {
    nombre: "Ceviche de Lubina Peruana",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN09",
    precio: 90,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Vino tinto ligero como Pinot Noir o un Shiraz joven",
  },
  {
    nombre: "Milhojas De Calabacín Frito",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN10",
    precio: 100,
    calificacion: 5,
    tiempoDePreparacion: "40 minutos",
    maridajeSugerido: "Vino blanco mineral como un Assyrtiko griego o un Sauvignon Blanc",
  },
  {
    nombre: "Tiras de Pollo Orgánicas",
    categoria: "Entrantes",
    imagen: "url_de_la_imagen",
    codigo: "EN11",
    precio: 85,
    calificacion: 5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Un vino tinto suave o una cerveza artesanal ligera",
  },

  // * Principales

  {
    nombre: "Loneta Con Chuletas De Cordero",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR01",
    precio: 50,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Un vino blanco dulce como Sauternes o Barsac",
  },
  {
    nombre: "Arroz General Tso Con Verduras",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR02",
    precio: 120,
    calificacion: 5,
    tiempoDePreparacion: "45 minutos",
    maridajeSugerido: "Vino blanco añejo como un Borgoña o Chardonnay",
  },
  {
    nombre: "Bulgur De Carne Estofado",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR03",
    precio: 150,
    calificacion: 5,
    tiempoDePreparacion: "50 minutos",
    maridajeSugerido: "Champán o un vino blanco complejo como Pouilly-Fuissé",
  },
  {
    nombre: "Lomo Wagyu 8-9",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR04",
    precio: 180,
    calificacion: 5,
    tiempoDePreparacion: "35 minutos",
    maridajeSugerido: "Vino tinto robusto como un Cabernet Sauvignon o Merlot",
  },
  {
    nombre: "Lienzo el Vegetariano",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR05",
    precio: 130,
    calificacion: 5,
    tiempoDePreparacion: "1 hora y 20 minutos",
    maridajeSugerido: "Vino tinto de reserva como un Rioja o un Shiraz",
  },
  {
    nombre: "Costilla Corta Hercules",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR06",
    precio: 140,
    calificacion: 5,
    tiempoDePreparacion: "40 minutos",
    maridajeSugerido: "Vino blanco fresco como un Pinot Gris o un Sauvignon Blanc",
  },
  {
    nombre: "Lienzo Wagyu de Trove",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR07",
    precio: 160,
    calificacion: 5,
    tiempoDePreparacion: "1 hora",
    maridajeSugerido: "Vino tinto sedoso como un Pinot Noir o un vino chino tradicional",
  },
  {
    nombre: "Arroz Claypot De Bacalao Negro",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR08",
    precio: 170,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Whisky de malta o un vino blanco con cuerpo como Viognier",
  },
  {
    nombre: "Cazuela De Salmon",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR09",
    precio: 190,
    calificacion: 5,
    tiempoDePreparacion: "45 minutos",
    maridajeSugerido: "Vino tinto con carácter como un Barolo o un Malbec",
  },
  {
    nombre: "Plato de marisco mixto Chargrill",
    categoria: "Principales",
    imagen: "url_de_la_imagen",
    codigo: "PR10",
    precio: 200,
    calificacion: 5,
    tiempoDePreparacion: "50 minutos",
    maridajeSugerido: "Vino blanco cremoso como un Riesling o un vino espumoso italiano",
  },
  
  // * Postre
  {
    nombre: "Pimiento de Padrón",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS01",
    precio: 50,
    calificacion: 5,
    tiempoDePreparacion: "10 minutos",
    maridajeSugerido: "Un vino blanco dulce como Sauternes o Barsac",
  },
  {
    nombre: "Camarones Dinamita",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS02",
    precio: 60,
    calificacion: 5,
    tiempoDePreparacion: "15 minutos",
    maridajeSugerido: "Vino de hielo o un Gewürztraminer",
  },
  {
    nombre: "Papas fritas",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS03",
    precio: 55,
    calificacion: 5,
    tiempoDePreparacion: "10 minutos",
    maridajeSugerido: "Oporto añejo o un Moscatel",
  },
  {
    nombre: "Champinones Asados",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS04",
    precio: 70,
    calificacion: 5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Cognac o un Armagnac",
  },
  {
    nombre: "Patata asada",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS05",
    precio: 65,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Café árabe o un té moruno",
  },
  {
    nombre: "Puré De Papa Puro",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS06",
    precio: 50,
    calificacion: 5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Champán rosado o un Riesling dulce",
  },
  {
    nombre: "Papas fritas con trufa",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS07",
    precio: 45,
    calificacion: 5,
    tiempoDePreparacion: "15 minutos",
    maridajeSugerido: "Té de menta o un vino dulce como Sauternes",
  },
  {
    nombre: "Mezcla De Vegetales A La Parrilla",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS08",
    precio: 55,
    calificacion: 5,
    tiempoDePreparacion: "25 minutos",
    maridajeSugerido: "Vino tinto dulce o un Madeira",
  },
  {
    nombre: "Verduras al vapor",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS09",
    precio: 65,
    calificacion: 5,
    tiempoDePreparacion: "20 minutos",
    maridajeSugerido: "Pedro Ximénez o un café expreso",
  },
  {
    nombre: "Brocolini salvaje",
    categoria: "postres",
    imagen: "url_de_la_imagen",
    codigo: "PS10",
    precio: 40,
    calificacion: 5,
    tiempoDePreparacion: "30 minutos",
    maridajeSugerido: "Vino espumoso o un té de jazmín",
  },

  // * Bebidas
  
  {
    nombre: "Volcán",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD01",
    precio: 50,
    calificacion: 5,
    tiempoDePreparacion: "5 minutos",
    maridajeSugerido: "Un vino blanco dulce como Sauternes o Barsac",
  },
  {
    nombre: "Oceano azul",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD02",
    precio: 80,
    calificacion: 5,
    tiempoDePreparacion: "10 minutos",
    maridajeSugerido: "Canapés ligeros o caviar",
  },
  {
    nombre: "Ven al lado oscuro",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD03",
    precio: 95,
    calificacion: 5,
    tiempoDePreparacion: "15 minutos",
    maridajeSugerido: "Frutas frescas o postres delicados",
  },
  {
    nombre: "Pandamonio",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD04",
    precio: 70,
    calificacion: 5,
    tiempoDePreparacion: "7 minutos",
    maridajeSugerido: "Chocolate oscuro o queso añejo",
  },
  {
    nombre: "Espacio X",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD05",
    precio: 65,
    calificacion: 5,
    tiempoDePreparacion: "12 minutos",
    maridajeSugerido: "Mariscos o ceviche",
  },
  {
    nombre: "Bloody Mary",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD06",
    precio: 55,
    calificacion: 5,
    tiempoDePreparacion: "5 minutos",
    maridajeSugerido: "Desayunos árabes o pastelería fina",
  },
  {
    nombre: "MARTINI DE CALABAZA",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD07",
    precio: 40,
    calificacion: 5,
    tiempoDePreparacion: "8 minutos",
    maridajeSugerido: "Postres ligeros o sorbetes",
  },
  {
    nombre: "Lucifer",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD08",
    precio: 60,
    calificacion: 5,
    tiempoDePreparacion: "14 minutos",
    maridajeSugerido: "Tapas o aperitivos salados",
  },
  {
    nombre: "Huevo de dragón",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD09",
    precio: 35,
    calificacion: 5,
    tiempoDePreparacion: "11 minutos",
    maridajeSugerido: "Baklava o dulces árabes",
  },
  {
    nombre: "Barbie",
    categoria: "Bebidas",
    imagen: "url_de_la_imagen",
    codigo: "BD10",
    precio: 45,
    calificacion: 5,
    tiempoDePreparacion: "9 minutos",
    maridajeSugerido: "Ensaladas frescas o platos vegetarianos",
  }
];
